name: Calls Release draft workflow

on:
    push

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Create fake files
        run: |
          echo "File RELEASE" > 1.txt
      - name: Create Release
        uses: softprops/action-gh-release@v2.5.0
        with:
          name: "Test Release ${{ github.run_number }}"
          draft: true
        env:
          GITHUB_TOKEN: ${{ github.token }}
  call-release:
    if: github.ref_type == 'tag'
    uses: ./.github/workflows/release-draft.yml
    needs: [create-release]
    with:
        id: ${{ github.run_number}}
